import type { PlatformAnalysis } from '@/types/pipeline';

// TODO: API 연동 후 제거
export const MOCK_ANALYSIS_RESULTS: PlatformAnalysis[] = [
  {
    platformId: 'naver-news',
    platformLabel: '네이버 뉴스',
    category: '뉴스',
    sirScore: 78,
    positive: 72,
    neutral: 18,
    negative: 10,
    flagged: [
      {
        title: '삼성전자 리콜 이슈, 소비자 불만 확산 중',
        url: 'https://news.naver.com/article/006',
        sentiment: 'negative',
        reason: '리콜 관련 부정 여론',
      },
    ],
  },
  {
    platformId: 'naver-stock-forum',
    platformLabel: '네이버증권 종목토론방',
    category: '커뮤니티',
    sirScore: 58,
    positive: 45,
    neutral: 25,
    negative: 30,
    flagged: [
      {
        title: '삼전 경영진 무능하다 진짜',
        url: 'https://finance.naver.com/item/board_read.nhn?code=005930&nid=10',
        sentiment: 'negative',
        reason: '경영진 비판 여론',
      },
      {
        title: '삼성 반도체 TSMC한테 밀리는 거 아님?',
        url: 'https://finance.naver.com/item/board_read.nhn?code=005930&nid=11',
        sentiment: 'caution',
        reason: '경쟁사 비교 부정 프레이밍',
      },
    ],
  },
  {
    platformId: 'paxnet',
    platformLabel: '팍스넷',
    category: '커뮤니티',
    sirScore: 65,
    positive: 50,
    neutral: 30,
    negative: 20,
    flagged: [],
  },
  {
    platformId: 'dcinside-stock',
    platformLabel: '디시인사이드 주식갤러리',
    category: '커뮤니티',
    sirScore: 42,
    positive: 30,
    neutral: 25,
    negative: 45,
    flagged: [
      {
        title: '삼성 망한다 ㅋㅋ 탈출각',
        url: 'https://gall.dcinside.com/board/view/?id=stock&no=5',
        sentiment: 'negative',
        reason: '극단적 부정 여론',
      },
      {
        title: '삼성 파운드리 수율 문제 심각하다는 소문',
        url: 'https://gall.dcinside.com/board/view/?id=stock&no=6',
        sentiment: 'caution',
        reason: '미확인 루머 확산',
      },
    ],
  },
  {
    platformId: 'ppomppu-stock',
    platformLabel: '뽐뿌 주식포럼',
    category: '커뮤니티',
    sirScore: 70,
    positive: 55,
    neutral: 30,
    negative: 15,
    flagged: [],
  },
  {
    platformId: 'google',
    platformLabel: '구글',
    category: '포털',
    sirScore: 80,
    positive: 70,
    neutral: 20,
    negative: 10,
    flagged: [],
  },
  {
    platformId: 'naver',
    platformLabel: '네이버',
    category: '포털',
    sirScore: 74,
    positive: 62,
    neutral: 23,
    negative: 15,
    flagged: [
      {
        title: '삼성전자 품질 이슈 연이어 발생…소비자 신뢰 하락',
        url: 'https://search.naver.com/search.nhn?query=samsung+quality',
        sentiment: 'caution',
        reason: '품질 관련 부정 검색 트렌드 상승',
      },
    ],
  },
  {
    platformId: 'youtube',
    platformLabel: '유튜브',
    category: 'SNS',
    sirScore: 68,
    positive: 55,
    neutral: 25,
    negative: 20,
    flagged: [
      {
        title: '[폭로] 삼성전자 내부 사정 다 알려드림',
        url: 'https://youtube.com/watch?v=flag1',
        sentiment: 'caution',
        reason: '자극적 제목 — 조회수 10만 이상',
      },
    ],
  },
  {
    platformId: 'instagram',
    platformLabel: '인스타그램',
    category: 'SNS',
    sirScore: 75,
    positive: 65,
    neutral: 25,
    negative: 10,
    flagged: [],
  },
  {
    platformId: 'naver-cafe',
    platformLabel: '네이버 카페',
    category: 'SNS',
    sirScore: 62,
    positive: 48,
    neutral: 30,
    negative: 22,
    flagged: [
      {
        title: '삼성전자 AS 최악 후기 공유',
        url: 'https://cafe.naver.com/samsung/complaint1',
        sentiment: 'negative',
        reason: 'CS 관련 부정 후기 다수 공감',
      },
    ],
  },
  {
    platformId: 'naver-blog',
    platformLabel: '네이버 블로그',
    category: 'SNS',
    sirScore: 76,
    positive: 68,
    neutral: 20,
    negative: 12,
    flagged: [],
  },
];
