name: Sync to Personal Fork

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Add remote-url
        run: |
          git remote add fork https://ImJaeOne:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/ImJaeOne/sir
          git config user.name ImJaeOne
          git config user.email ${{ secrets.EMAIL }}

      - name: Push changes to forked-repo
        run: |
          git push -f fork main

      - name: Clean up
        run: |
          git remote remove fork
